// examples/todo/output/next-js/components/src/components/todos.lite.tsx
import * as todosState from "../shared/todos-state.lite";
import * as Todo from "./todo.lite";

export default function Todos(props) {
  return (
    <>
      <section className="main">
        {Boolean(todosState.todos.length) && (
          <>
            <input
              className="toggle-all"
              type="checkbox"
              checked={todosState.allCompleted}
              onClick={(event) => {
                {
                  const newValue = !todosState.allCompleted;

                  for (const todoItem of todosState.todos) {
                    todoItem.completed = newValue;
                  }
                }
              }}
            />
          </>
        )}

        <ul className="todo-list">
          {todosState.todos.map((todo) => (
            <>
              <Todo todo={todo}></Todo>
            </>
          ))}
        </ul>
      </section>
    </>
  );
}

// examples/todo/output/angular/src/components/todos.lite.tsx
import { Component } from "@angular/core";

import todosState from "../shared/todos-state.lite";
import Todo from "./todo.lite";

@Component({
  selector: "todos",
  template: `
    <section class="main">
      <ng-container *ngIf="todosState.todos.length">
        <input
          class="toggle-all"
          type="checkbox"
          [checked]="todosState.allCompleted"
          (click)="
      const newValue = !todosState.allCompleted;

      for (const todoItem of todosState.todos) {
        todoItem.completed = newValue;
      }
    "
        />
      </ng-container>

      <ul class="todo-list">
        <ng-container *ngFor="let todo of todosState.todos">
          <todo [todo]="todo"></todo>
        </ng-container>
      </ul>
    </section>
  `,
})
export default class Todos {}
