// packages/starter/template/servers/svelte/src/App.svelte
<script lang="ts">
  import { AutoComplete, Todos } from '@template/library-svelte';
  import AutocompleteChild from './AutocompleteChild.svelte';
  import { mockApi } from './mockApi';
</script>

<div>
  <img src="../svelte-logo.png" width={50} alt="svelte logo" />
  {#if window.location.pathname.endsWith('autocomplete')}
    <AutoComplete
      getValues={mockApi}
      renderChild={AutocompleteChild}
      transformData={(x) => x.name}
    />
  {:else}
    <Todos />
  {/if}
</div>

// packages/starter/template/servers/react/src/App.jsx
import { AutoComplete, Todos } from '@template/library-react';

function App() {
  const getValues = async () => {
    return ['Hello', 'Modern', 'Frontends', 'Live!'];
  };
  const getComponentForPath = (path) => {
    switch (path) {
      case '/todo':
        return <Todos />;
      case '/autocomplete':
        return (
          <AutoComplete
            renderChild={(props) => <span>{props.item}</span>}
            getValues={getValues}
            transformData={(x) => x}
          />
        );
      default:
        return <Todos />;
    }
  };

  return (
    <div>
      <img src="../react-logo.png" width={50} />
      {getComponentForPath(window.location.pathname)}
    </div>
  );
}

export default App;
