// examples/todo/output/angular/src/components/todo.js
import { Component, Input } from "@angular/core";

import todosState from "../shared/todos-state.lite";

@Component({
  selector: "todo",
  template: `
    <li
      [class]="\`\${todo.completed ? 'completed' : ''} \${editing ? 'editing' : ''}\`"
    >
      <div class="view">
        <input
          class="toggle"
          type="checkbox"
          [checked]="todo.completed"
          (click)="
         toggle();
       "
        />

        <label
          (dblclick)="
         editing = true;
       "
        >
          {{todo.text}}
        </label>

        <button
          class="destroy"
          (click)="
         todosState.todos.splice(todosState.todos.indexOf(todo));
       "
        ></button>
      </div>

      <ng-container *ngIf="editing">
        <input
          class="edit"
          [value]="todo.text"
          (blur)="
         editing = false;
       "
          (keyup)="
         todo.text = $event.target.value;
       "
        />
      </ng-container>
    </li>
  `,
})
export default class Todo {
  @Input() todo: any;

  editing = false;
  toggle() {
    this.todo.completed = !this.todo.completed;
  }
}

// examples/todo/output/vue/nuxt2/src/components/todo.vue
<template>
  <li
    :class="
      _classStringToObject(
        `${this.todo.completed ? 'completed' : ''} ${
          this.editing ? 'editing' : ''
        }`
      )
    "
  >
    <div class="view">
      <input
        class="toggle"
        type="checkbox"
        :checked="todo.completed"
        @click="toggle()"
      />
      <label @dblclick="editing = true">
        {{ todo.text }}
      </label>
      <button
        class="destroy"
        @click="todosState.todos.splice(todosState.todos.indexOf(todo))"
      ></button>
    </div>

    <input
      class="edit"
      v-if="editing"
      :value="todo.text"
      @blur="editing = false"
      @keyup="todo.text = $event.target.value"
    />
  </li>
</template>
<script>
import todosState from "../shared/todos-state";

export default {
  name: "todo",

  props: ["todo"],

  data: () => ({ editing: false, todosState }),

  methods: {
    toggle() {
      this.todo.completed = !this.todo.completed;
    },
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>
