// packages/core/integration/frameworks/next-js/pages/home.jsx
import { useState } from "react";

export default function Home(props) {
  const [name, setName] = useState(() => "Steve");

  return (
    <>
      <style jsx>{`
        .div-1 {
          text-align: center;
        }
      `}</style>
      <div className="div-1">
        <h2>
          Hello,
          {name}!
        </h2>

        <input
          value={name}
          onChange={(event) => {
            setName(event.target.value);
          }}
        />
      </div>
    </>
  );
}

// packages/core/integration/frameworks/solid/examples/shared/src/components/Home.js
import { createMutable, Show, For } from "solid-js";
import { css } from "solid-styled-components";

export default function Home() {
  const state = createMutable({ name: "Steve" });

  return (
    <div
      class={css({
        textAlign: "center",
      })}
    >
      <h2>
        Hello,
        {state.name}!
      </h2>

      <input
        value={state.name}
        onChange={(event) => (state.name = event.target.value)}
      />
    </div>
  );
}
