// packages/starter/template/library/packages/react/src/autocomplete/autocomplete.tsx
"use client";
import * as React from "react";
import { useState, useEffect } from "react";

export type Props = {
  getValues: (input: string) => Promise<any[]>;
  renderChild?: any;
  transformData: (item: any) => string;
};

function Example2(props: Props) {
  const [showSuggestions, setShowSuggestions] = useState(() => false);

  const [suggestions, setSuggestions] = useState(() => []);

  function setInputValue(value: string) {
    setInput(value);
  }

  function handleClick(item: any) {
    setInputValue(props.transformData(item));
    setShowSuggestions(false);
  }

  const [Input, setInput] = useState(() => "");

  useEffect(() => {
    props.getValues(input).then((x) => {
      const filteredX = x.filter((data) => {
        return props
          .transformData(data)
          .toLowerCase()
          .includes(input.toLowerCase());
      });
      setSuggestions(filteredX);
    });
  }, [input, props.getValues]);

  return (
    <>
      <div className="div">
        <link
          href="/Users/samijaber/code/work/mitosis/examples/talk/apps/src/tailwind.min.css"
          rel="stylesheet"
        />
        Autocomplete:
        <div className="relative">
          <Input
            className="shadow-md rounded w-full px-4 py-2 border border-black"
            value={input}
            onChange={(event) => setInput(event.target.value)}
            onFocus={(event) => setShowSuggestions(true)}
          />

          <button
            className="absolute right-4 h-full"
            onClick={(event) => {
              setInput("");
              setShowSuggestions(false);
            }}
          >
            X
          </button>
        </div>
        {suggestions.length > 0 && showSuggestions ? (
          <>
            <ul className="shadow-md rounded h-40 overflow-scroll">
              {suggestions?.map((item) => (
                <li
                  className="border-gray-200 border-b flex items-center cursor-pointer hover:bg-gray-100 p-2"
                  onClick={(event) => handleClick(item)}
                >
                  {props.renderChild ? (
                    <>
                      <props.renderChild item={item} />
                    </>
                  ) : (
                    <span>{props.transformData(item)}</span>
                  )}
                </li>
              ))}
            </ul>
          </>
        ) : null}
      </div>
      <style jsx>{`
        .div {
          padding: 10px;
        }
      `}</style>
    </>
  );
}

export default Example2;

// packages/starter/template/library/packages/svelte/package/autocomplete/autocomplete.svelte
<script context="module"></script>

<script>export let transformData;
export let renderChild;
export let getValues;
function setInputValue(value) {
    input = value;
}
function handleClick(item) {
    setInputValue(transformData(item));
    showSuggestions = false;
}
let showSuggestions = false;
let suggestions = [];
let input = "";
function onUpdateFn_0() {
    getValues(input).then((x) => {
        const filteredX = x.filter((data) => {
            return transformData(data).toLowerCase().includes(input.toLowerCase());
        });
        suggestions = filteredX;
    });
}
$: onUpdateFn_0(...[input, getValues]);
</script>

<div class="div">
  <link
    href="/Users/samijaber/code/work/mitosis/examples/talk/apps/src/tailwind.min.css"
    rel="stylesheet"
  />
  Autocomplete:
  <div class="relative">
    <input
      class="shadow-md rounded w-full px-4 py-2 border border-black"
      on:focus={(event) => {
        showSuggestions = true;
      }}
      bind:value={input}
    />
    <button
      class="absolute right-4 h-full"
      on:click={(event) => {
        input = "";
        showSuggestions = false;
      }}
    >
      X
    </button>
  </div>

  {#if suggestions.length > 0 && showSuggestions}
    <ul class="shadow-md rounded h-40 overflow-scroll">
      {#each suggestions as item}
        <li
          class="border-gray-200 border-b flex items-center cursor-pointer hover:bg-gray-100 p-2"
          on:click={(event) => {
            handleClick(item);
          }}
        >
          {#if renderChild}
            <svelte:component this={renderChild} {item} />
          {:else}
            <span>{transformData(item)}</span>
          {/if}
        </li>
      {/each}
    </ul>
  {/if}
</div>

<style>
  .div {
    padding: 10px;
  }
</style>
