// packages/e2e-react/src/App.tsx
// Mitosis output for not yet include .d.ts, so ignore the types when importing.
// @ts-ignore
import { MyComponent } from '@builder.io/e2e-app/react';
import React from 'react';

// Accommodate Mitosis output - assumes React is a global.
window.React = React;

function App() {
  return <MyComponent></MyComponent>;
}

export default App;

// packages/e2e-qwik/src/components/app/app.tsx
import { component$, Host } from '@builder.io/qwik';

// Mitosis output for not yet include .d.ts, so ignore the types when importing.
// @ts-ignore
// import { MyComponent } from '@builder.io/e2e-app-qwik-output';

// Temporary import of the source code instead of build output;
// This works with vite dev, but not vite build.
import { MyComponent } from '@builder.io/e2e-app/qwik';

export const App = component$(() => {
  return (
    <Host>
      <MyComponent></MyComponent>
    </Host>
  );
});
