// packages/core/integration/frameworks/angular/src/app/home.ts
import { Component } from "@angular/core";

@Component({
  selector: "home",
  template: `
    <div class="div-1">
      <h2>Hello, {{name}} !</h2>

      <input [value]="name" (input)="name = $event.target.value" />
    </div>
  `,
  styles: [
    `
      .div-1 {
        text-align: center;
        color: steelblue;
      }
    `,
  ],
})
export default class Home {
  name = "Steve";
}

// packages/core/integration/frameworks/next-js/pages/home.jsx
import { useState } from "react";

export default function Home(props) {
  const [name, setName] = useState(() => "Steve");

  return (
    <>
      <style jsx>{`
        .div-1 {
          text-align: center;
          color: steelblue;
        }
      `}</style>
      <div className="div-1">
        <h2>
          Hello,
          {name}!
        </h2>

        <input
          value={name}
          onChange={(event) => {
            setName(event.target.value);
          }}
        />
      </div>
    </>
  );
}
