// examples/talk/react-app/src/App.tsx
import { Todos, AutoComplete } from '@builder.io/talk-app-react';

function App() {
  const getValues = async () => {
    return ['foo', 'bar', 'baz'];
  };
  const getComponentForPath = (path: string) => {
    switch (path) {
      case '/todo':
        return <Todos />;
      case '/autocomplete':
        return (
          <AutoComplete
            renderChild={(props) => <span>{props.item}</span>}
            getValues={getValues}
            transformData={(x) => x}
          />
        );
      default:
        return <Todos />;
    }
  };

  return (
    <div>
      <img src="../react-logo.png" width={50} />
      {getComponentForPath(window.location.pathname)}
    </div>
  );
}

export default App;

// examples/talk/svelte-app/src/App.svelte
<script lang="ts">
  import { AutoComplete, Todos } from '@builder.io/talk-app-svelte';
  import AutocompleteChild from './AutocompleteChild.svelte';
  import { mockApi } from './mockApi';
</script>

<div>
  <img src="../svelte-logo.png" width={50} alt="svelte logo" />
  {#if window.location.pathname.endsWith('autocomplete')}
    <AutoComplete
      getValues={mockApi}
      renderChild={AutocompleteChild}
      transformData={(x) => x.name}
    />
  {:else}
    <Todos />
  {/if}
</div>
