// examples/todo/output/vue/nuxt2/src/components/todos.vue
<template>
  <section class="main">
    <input
      class="toggle-all"
      type="checkbox"
      v-if="todosState.todos.length"
      :checked="todosState.allCompleted"
      @click="
        const newValue = !todosState.allCompleted;

        for (const todoItem of todosState.todos) {
          todoItem.completed = newValue;
        }
      "
    />

    <ul class="todo-list">
      <todo
        v-for="(todo, index) in todosState.todos"
        :todo="todo"
        :key="index"
      ></todo>
    </ul>
  </section>
</template>
<script>
import todosState from "../shared/todos-state";
import Todo from "./todo";

export default {
  name: "todos",
  components: { todo: async () => Todo },

  data: () => ({ todosState }),
};
</script>

// examples/todo/output/next-js/components/src/components/todos.tsx
import todosState from "../shared/todos-state";
import Todo from "./todo";

export default function Todos(props) {
  return (
    <>
      <section className="main">
        {Boolean(todosState.todos.length) && (
          <>
            <input
              className="toggle-all"
              type="checkbox"
              checked={todosState.allCompleted}
              onClick={(event) => {
                {
                  const newValue = !todosState.allCompleted;

                  for (const todoItem of todosState.todos) {
                    todoItem.completed = newValue;
                  }
                }
              }}
            />
          </>
        )}

        <ul className="todo-list">
          {todosState.todos.map((todo) => (
            <>
              <Todo todo={todo}></Todo>
            </>
          ))}
        </ul>
      </section>
    </>
  );
}
