// examples/todo/output/angular/src/components/todo.js
import { Component, Input } from "@angular/core";

import todosState from "../shared/todos-state.lite";

@Component({
  selector: "todo",
  template: `
    <li
      [class]="\`\${todo.completed ? 'completed' : ''} \${editing ? 'editing' : ''}\`"
    >
      <div class="view">
        <input
          class="toggle"
          type="checkbox"
          [checked]="todo.completed"
          (click)="
         toggle();
       "
        />

        <label
          (dblclick)="
         editing = true;
       "
        >
          {{todo.text}}
        </label>

        <button
          class="destroy"
          (click)="
         todosState.todos.splice(todosState.todos.indexOf(todo));
       "
        ></button>
      </div>

      <ng-container *ngIf="editing">
        <input
          class="edit"
          [value]="todo.text"
          (blur)="
         editing = false;
       "
          (keyup)="
         todo.text = $event.target.value;
       "
        />
      </ng-container>
    </li>
  `,
})
export default class Todo {
  @Input() todo: any;

  editing = false;
  toggle() {
    this.todo.completed = !this.todo.completed;
  }
}

// examples/todo/output/next-js/components/src/components/todo.tsx
import { useState } from "react";
import todosState from "../shared/todos-state.lite";

export default function Todo(props) {
  const [editing, setEditing] = useState(() => false);
  function toggle() {
    props.todo.completed = !props.todo.completed;
  }

  return (
    <>
      <li
        className={`${props.todo.completed ? "completed" : ""} ${
          editing ? "editing" : ""
        }`}
      >
        <div className="view">
          <input
            className="toggle"
            type="checkbox"
            checked={props.todo.completed}
            onClick={(event) => {
              toggle();
            }}
          />

          <label
            onDblClick={(event) => {
              setEditing(true);
            }}
          >
            {props.todo.text}
          </label>

          <button
            className="destroy"
            onClick={(event) => {
              todosState.todos.splice(todosState.todos.indexOf(props.todo));
            }}
          ></button>
        </div>

        {Boolean(editing) && (
          <>
            <input
              className="edit"
              value={props.todo.text}
              onBlur={(event) => {
                setEditing(false);
              }}
              onKeyUp={(event) => {
                props.todo.text = event.target.value;
              }}
            />
          </>
        )}
      </li>
    </>
  );
}
