// examples/todo/output/next-js/components/src/components/todo.tsx
import { useState } from "react";
import todosState from "../shared/todos-state";

export default function Todo(props) {
  const [editing, setEditing] = useState(() => false);
  function toggle() {
    props.todo.completed = !props.todo.completed;
  }

  return (
    <>
      <li
        className={`${props.todo.completed ? "completed" : ""} ${
          editing ? "editing" : ""
        }`}
      >
        <div className="view">
          <input
            className="toggle"
            type="checkbox"
            checked={props.todo.completed}
            onClick={(event) => {
              {
                toggle();
              }
            }}
          />

          <label
            onDblClick={(event) => {
              {
                setEditing(true);
              }
            }}
          >
            {props.todo.text}
          </label>

          <button
            className="destroy"
            onClick={(event) => {
              {
                todosState.todos.splice(todosState.todos.indexOf(props.todo));
              }
            }}
          ></button>
        </div>

        {Boolean(editing) && (
          <>
            <input
              className="edit"
              value={props.todo.text}
              onBlur={(event) => {
                {
                  setEditing(false);
                }
              }}
              onKeyUp={(event) => {
                {
                  props.todo.text = event.target.value;
                }
              }}
            />
          </>
        )}
      </li>
    </>
  );
}

// examples/todo/output/solid/src/components/todo.jsx
import { Show } from "solid-js";
import { createMutable } from "solid-js/store";
import todosState from "../shared/todos-state";

function Todo(props) {
  const state = createMutable({
    editing: false,

    toggle() {
      props.todo.completed = !props.todo.completed;
    }

  });
  return <li class={`${props.todo.completed ? "completed" : ""} ${state.editing ? "editing" : ""}`}>
      <div class="view">
        <input class="toggle" type="checkbox" checked={props.todo.completed} onClick={event => {
        state.toggle();
      }} />
        <label onDblClick={event => {
        state.editing = true;
      }}>
          {props.todo.text}
        </label>
        <button class="destroy" onClick={event => {
        todosState.todos.splice(todosState.todos.indexOf(props.todo));
      }}></button>
      </div>
      <Show when={state.editing}>
        <input class="edit" value={props.todo.text} onBlur={event => {
        state.editing = false;
      }} onKeyUp={event => {
        props.todo.text = event.target.value;
      }} />
      </Show>
    </li>;
}

export default Todo;
