// examples/todo/output/next-js/components/src/components/todos.lite.tsx
import * as todosState from "../shared/todos-state.lite";
import * as Todo from "./todo.lite";

export default function Todos(props) {
  return (
    <>
      <section className="main">
        {Boolean(todosState.todos.length) && (
          <>
            <input
              className="toggle-all"
              type="checkbox"
              checked={todosState.allCompleted}
              onClick={(event) => {
                {
                  const newValue = !todosState.allCompleted;

                  for (const todoItem of todosState.todos) {
                    todoItem.completed = newValue;
                  }
                }
              }}
            />
          </>
        )}

        <ul className="todo-list">
          {todosState.todos.map((todo) => (
            <>
              <Todo todo={todo}></Todo>
            </>
          ))}
        </ul>
      </section>
    </>
  );
}

// examples/todo/output/solid/src/components/todos.lite.tsx
import { Show, For } from "solid-js";

import todosState from "../shared/todos-state.lite";
import Todo from "./todo.lite";

function Todos(props) {
  return (
    <section class="main">
      <Show when={todosState.todos.length}>
        <input
          class="toggle-all"
          type="checkbox"
          checked={todosState.allCompleted}
          onClick={(event) => {
            const newValue = !todosState.allCompleted;

            for (const todoItem of todosState.todos) {
              todoItem.completed = newValue;
            }
          }}
        />
      </Show>
      <ul class="todo-list">
        <For each={todosState.todos}>
          {(todo, _index) => {
            const index = _index();
            return <Todo todo={todo}></Todo>;
          }}
        </For>
      </ul>
    </section>
  );
}

export default Todos;
